/**
 * Copyright (c) 2024 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef ZEPHYR_INCLUDE_DRIVERS_CLOCK_CONTROL_CLOCK_CONTROL_MCHP_V1_H_
#define ZEPHYR_INCLUDE_DRIVERS_CLOCK_CONTROL_CLOCK_CONTROL_MCHP_V1_H_

#include <zephyr/kernel.h>
#include <zephyr/drivers/clock_control.h>

/** @brief Clocks handled by the CLK peripheral.
 *
 * Structure which can be used as a sys argument in clock_control API.
 */
struct clock_control_mchp_subsys_t {
	/* clock controller subsys device */
	const struct device *dev;
	/* clock id related to subsys */
	uint32_t id;
};

#if defined(CONFIG_SOC_SERIES_MCHP_SAME54)
/* Include rquired header files */
#include <dt-bindings/clock/sam/same54/mchp_same54_clock.h>

/** @brief Clocks handled by the MCLK peripheral.
 *
 * This can be used as id in clock_control_mchp_subsys_t clock_control API.
 */
typedef enum {
	/* MCLK Controller */
	CLOCK_CONTROL_MCHP_V1_MCLK_CPU = CLOCK_MCHP_SAME54_MCLK_CPU,
	CLOCK_CONTROL_MCHP_V1_MCLK_HS = CLOCK_MCHP_SAME54_MCLK_HS,

	/* AHB Clock */
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_HPB0 = CLOCK_MCHP_SAME54_MCLK_AHB_HPB0,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_HPB1 = CLOCK_MCHP_SAME54_MCLK_AHB_HPB1,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_HPB2 = CLOCK_MCHP_SAME54_MCLK_AHB_HPB2,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_HPB3 = CLOCK_MCHP_SAME54_MCLK_AHB_HPB3,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_DSU = CLOCK_MCHP_SAME54_MCLK_AHB_DSU,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_NVMCTRL = CLOCK_MCHP_SAME54_MCLK_AHB_NVMCTRL,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_CMCC = CLOCK_MCHP_SAME54_MCLK_AHB_CMCC,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_DMAC = CLOCK_MCHP_SAME54_MCLK_AHB_DMAC,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_USB = CLOCK_MCHP_SAME54_MCLK_AHB_USB,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_PAC = CLOCK_MCHP_SAME54_MCLK_AHB_PAC,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_QSPI = CLOCK_MCHP_SAME54_MCLK_AHB_QSPI,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_GMAC = CLOCK_MCHP_SAME54_MCLK_AHB_GMAC,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_SDHC0 = CLOCK_MCHP_SAME54_MCLK_AHB_SDHC0,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_SDHC1 = CLOCK_MCHP_SAME54_MCLK_AHB_SDHC1,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_CAN0 = CLOCK_MCHP_SAME54_MCLK_AHB_CAN0,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_CAN1 = CLOCK_MCHP_SAME54_MCLK_AHB_CAN1,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_PUKCC = CLOCK_MCHP_SAME54_MCLK_AHB_PUKCC,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_QSPI_2X = CLOCK_MCHP_SAME54_MCLK_AHB_QSPI_2X,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_NVMCTRL_SMEEPROM =
		CLOCK_MCHP_SAME54_MCLK_AHB_NVMCTRL_SMEEPROM,
	CLOCK_CONTROL_MCHP_V1_MCLK_AHB_NVMCTRL_CACHE = CLOCK_MCHP_SAME54_MCLK_AHB_NVMCTRL_CACHE,

	/* APBA Clocks */
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_PAC = CLOCK_MCHP_SAME54_MCLK_APBA_PAC,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_PM = CLOCK_MCHP_SAME54_MCLK_APBA_PM,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_MCLK = CLOCK_MCHP_SAME54_MCLK_APBA_MCLK,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_RSTC = CLOCK_MCHP_SAME54_MCLK_APBA_RSTC,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_OSCCTRL = CLOCK_MCHP_SAME54_MCLK_APBA_OSCCTRL,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_OSC32KCTRL = CLOCK_MCHP_SAME54_MCLK_APBA_OSC32KCTRL,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_SUPC = CLOCK_MCHP_SAME54_MCLK_APBA_SUPC,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_GCLK = CLOCK_MCHP_SAME54_MCLK_APBA_GCLK,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_WDT = CLOCK_MCHP_SAME54_MCLK_APBA_WDT,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_RTC = CLOCK_MCHP_SAME54_MCLK_APBA_RTC,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_EIC = CLOCK_MCHP_SAME54_MCLK_APBA_EIC,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_FREQM = CLOCK_MCHP_SAME54_MCLK_APBA_FREQM,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_SERCOM0 = CLOCK_MCHP_SAME54_MCLK_APBA_SERCOM0,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_SERCOM1 = CLOCK_MCHP_SAME54_MCLK_APBA_SERCOM1,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_TC0 = CLOCK_MCHP_SAME54_MCLK_APBA_TC0,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBA_TC1 = CLOCK_MCHP_SAME54_MCLK_APBA_TC1,

	/* APBB Clocks */
	CLOCK_CONTROL_MCHP_V1_MCLK_APBB_USB = CLOCK_MCHP_SAME54_MCLK_APBB_USB,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBB_DSU = CLOCK_MCHP_SAME54_MCLK_APBB_DSU,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBB_NVMCTRL = CLOCK_MCHP_SAME54_MCLK_APBB_NVMCTRL,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBB_PORT = CLOCK_MCHP_SAME54_MCLK_APBB_PORT,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBB_EVSYS = CLOCK_MCHP_SAME54_MCLK_APBB_EVSYS,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBB_SERCOM2 = CLOCK_MCHP_SAME54_MCLK_APBB_SERCOM2,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBB_SERCOM3 = CLOCK_MCHP_SAME54_MCLK_APBB_SERCOM3,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBB_TCC0 = CLOCK_MCHP_SAME54_MCLK_APBB_TCC0,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBB_TCC1 = CLOCK_MCHP_SAME54_MCLK_APBB_TCC1,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBB_TC2 = CLOCK_MCHP_SAME54_MCLK_APBB_TC2,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBB_TC3 = CLOCK_MCHP_SAME54_MCLK_APBB_TC3,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBB_RAMECC = CLOCK_MCHP_SAME54_MCLK_APBB_RAMECC,

	/* APBC Clocks */
	CLOCK_CONTROL_MCHP_V1_MCLK_APBC_GMAC = CLOCK_MCHP_SAME54_MCLK_APBC_GMAC,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBC_TCC2 = CLOCK_MCHP_SAME54_MCLK_APBC_TCC2,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBC_TCC3 = CLOCK_MCHP_SAME54_MCLK_APBC_TCC3,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBC_TC4 = CLOCK_MCHP_SAME54_MCLK_APBC_TC4,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBC_TC5 = CLOCK_MCHP_SAME54_MCLK_APBC_TC5,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBC_PDEC = CLOCK_MCHP_SAME54_MCLK_APBC_PDEC,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBC_AC = CLOCK_MCHP_SAME54_MCLK_APBC_AC,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBC_AES = CLOCK_MCHP_SAME54_MCLK_APBC_AES,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBC_TRNG = CLOCK_MCHP_SAME54_MCLK_APBC_TRNG,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBC_ICM = CLOCK_MCHP_SAME54_MCLK_APBC_ICM,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBC_QSPI = CLOCK_MCHP_SAME54_MCLK_APBC_QSPI,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBC_CCL = CLOCK_MCHP_SAME54_MCLK_APBC_CCL,

	/* APBD Clocks */
	CLOCK_CONTROL_MCHP_V1_MCLK_APBD_SERCOM4 = CLOCK_MCHP_SAME54_MCLK_APBD_SERCOM4,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBD_SERCOM5 = CLOCK_MCHP_SAME54_MCLK_APBD_SERCOM5,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBD_SERCOM6 = CLOCK_MCHP_SAME54_MCLK_APBD_SERCOM6,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBD_SERCOM7 = CLOCK_MCHP_SAME54_MCLK_APBD_SERCOM7,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBD_TCC4 = CLOCK_MCHP_SAME54_MCLK_APBD_TCC4,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBD_TC6 = CLOCK_MCHP_SAME54_MCLK_APBD_TC6,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBD_TC7 = CLOCK_MCHP_SAME54_MCLK_APBD_TC7,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBD_ADC0 = CLOCK_MCHP_SAME54_MCLK_APBD_ADC0,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBD_ADC1 = CLOCK_MCHP_SAME54_MCLK_APBD_ADC1,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBD_DAC = CLOCK_MCHP_SAME54_MCLK_APBD_DAC,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBD_I2S = CLOCK_MCHP_SAME54_MCLK_APBD_I2S,
	CLOCK_CONTROL_MCHP_V1_MCLK_APBD_PCC = CLOCK_MCHP_SAME54_MCLK_APBD_PCC,
} clock_control_mchp_mclk_sys_t;

/** @brief Clocks handled by the OSCCTRL peripheral.
 *
 * This can be used as id in clock_control_mchp_subsys_t clock_control API.
 */
typedef enum {
	/* OSCCTRL Clock Controller */
	CLOCK_CONTROL_MCHP_V1_OSCCTRL_XOSC0 = CLOCK_MCHP_SAME54_OSCCTRL_XOSC0,
	CLOCK_CONTROL_MCHP_V1_OSCCTRL_XOSC1 = CLOCK_MCHP_SAME54_OSCCTRL_XOSC1,
	/* OSCCTRL Clock Controller - DFLL */
	CLOCK_CONTROL_MCHP_V1_OSCCTRL_DFLL = CLOCK_MCHP_SAME54_OSCCTRL_DFLL,
	/* OSCCTRL Clock Controller - DPLL */
	CLOCK_CONTROL_MCHP_V1_OSCCTRL_FDPLL0 = CLOCK_MCHP_SAME54_OSCCTRL_FDPLL0,
	CLOCK_CONTROL_MCHP_V1_OSCCTRL_FDPLL1 = CLOCK_MCHP_SAME54_OSCCTRL_FDPLL1,
} clock_control_mchp_oscctrl_sys_t;

/** @brief Clocks handled by the OSC32KCTRL peripheral.
 *
 * This can be used as id in clock_control_mchp_subsys_t clock_control API.
 */
typedef enum {
	/* OSC32KCTRL Clock Controller */
	CLOCK_CONTROL_MCHP_V1_OSC32KCTRL_XOSC32K = CLOCK_MCHP_SAME54_OSC32KCTRL_XOSC32K,
	CLOCK_CONTROL_MCHP_V1_OSC32KCTRL_XOSC32K_OUT32K =
		CLOCK_MCHP_SAME54_OSC32KCTRL_XOSC32K_OUT32K,
	CLOCK_CONTROL_MCHP_V1_OSC32KCTRL_XOSC32K_OUT1K = CLOCK_MCHP_SAME54_OSC32KCTRL_XOSC32K_OUT1K,
	CLOCK_CONTROL_MCHP_V1_OSC32KCTRL_OSCULP32K = CLOCK_MCHP_SAME54_OSC32KCTRL_OSCULP32K,
	CLOCK_CONTROL_MCHP_V1_OSC32KCTRL_OSCULP32K_OUT32K =
		CLOCK_MCHP_SAME54_OSC32KCTRL_OSCULP32K_OUT32K,
	CLOCK_CONTROL_MCHP_V1_OSC32KCTRL_OSCULP32K_OUT1K =
		CLOCK_MCHP_SAME54_OSC32KCTRL_OSCULP32K_OUT1K,
	CLOCK_CONTROL_MCHP_V1_OSC32KCTRL_RTC = CLOCK_MCHP_SAME54_OSC32KCTRL_RTC,
} clock_control_mchp_osc32kctrl_sys_t;

/** @brief Clocks handled by the GCLK peripheral.
 *
 * This can be used as id in clock_control_mchp_subsys_t clock_control API.
 */
typedef enum {
	/* GCLK Controller */
	CLOCK_CONTROL_MCHP_V1_GCLK_GEN0 = CLOCK_MCHP_SAME54_GCLK_GEN0,
	CLOCK_CONTROL_MCHP_V1_GCLK_GEN1 = CLOCK_MCHP_SAME54_GCLK_GEN1,
	CLOCK_CONTROL_MCHP_V1_GCLK_GEN2 = CLOCK_MCHP_SAME54_GCLK_GEN2,
	CLOCK_CONTROL_MCHP_V1_GCLK_GEN3 = CLOCK_MCHP_SAME54_GCLK_GEN3,
	CLOCK_CONTROL_MCHP_V1_GCLK_GEN4 = CLOCK_MCHP_SAME54_GCLK_GEN4,
	CLOCK_CONTROL_MCHP_V1_GCLK_GEN5 = CLOCK_MCHP_SAME54_GCLK_GEN5,
	CLOCK_CONTROL_MCHP_V1_GCLK_GEN6 = CLOCK_MCHP_SAME54_GCLK_GEN6,
	CLOCK_CONTROL_MCHP_V1_GCLK_GEN7 = CLOCK_MCHP_SAME54_GCLK_GEN7,
	CLOCK_CONTROL_MCHP_V1_GCLK_GEN8 = CLOCK_MCHP_SAME54_GCLK_GEN8,
	CLOCK_CONTROL_MCHP_V1_GCLK_GEN9 = CLOCK_MCHP_SAME54_GCLK_GEN9,
	CLOCK_CONTROL_MCHP_V1_GCLK_GEN10 = CLOCK_MCHP_SAME54_GCLK_GEN10,
	CLOCK_CONTROL_MCHP_V1_GCLK_GEN11 = CLOCK_MCHP_SAME54_GCLK_GEN11,

	/* Peripheral Clocks which needs GCLK as input */
	CLOCK_CONTROL_MCHP_V1_GCLK_OSCCTRL_DFLL48 = CLOCK_MCHP_SAME54_GCLK_OSCCTRL_DFLL48,
	CLOCK_CONTROL_MCHP_V1_GCLK_OSCCTRL_FDPLL0 = CLOCK_MCHP_SAME54_GCLK_OSCCTRL_FDPLL0,
	CLOCK_CONTROL_MCHP_V1_GCLK_OSCCTRL_FDPLL1 = CLOCK_MCHP_SAME54_GCLK_OSCCTRL_FDPLL1,
	CLOCK_CONTROL_MCHP_V1_GCLK_OSCCTRL_SLOW = CLOCK_MCHP_SAME54_GCLK_OSCCTRL_SLOW,
	CLOCK_CONTROL_MCHP_V1_GCLK_EIC = CLOCK_MCHP_SAME54_GCLK_EIC,
	CLOCK_CONTROL_MCHP_V1_GCLK_FREQM_MSR = CLOCK_MCHP_SAME54_GCLK_FREQM_MSR,
	CLOCK_CONTROL_MCHP_V1_GCLK_FREQM_REF = CLOCK_MCHP_SAME54_GCLK_FREQM_REF,
	CLOCK_CONTROL_MCHP_V1_GCLK_SERCOM0_CORE = CLOCK_MCHP_SAME54_GCLK_SERCOM0_CORE,
	CLOCK_CONTROL_MCHP_V1_GCLK_SERCOM1_CORE = CLOCK_MCHP_SAME54_GCLK_SERCOM1_CORE,
	CLOCK_CONTROL_MCHP_V1_GCLK_TC0_TC1 = CLOCK_MCHP_SAME54_GCLK_TC0_TC1,
	CLOCK_CONTROL_MCHP_V1_GCLK_USB = CLOCK_MCHP_SAME54_GCLK_USB,
	CLOCK_CONTROL_MCHP_V1_GCLK_EVSYS0 = CLOCK_MCHP_SAME54_GCLK_EVSYS0,
	CLOCK_CONTROL_MCHP_V1_GCLK_EVSYS1 = CLOCK_MCHP_SAME54_GCLK_EVSYS1,
	CLOCK_CONTROL_MCHP_V1_GCLK_EVSYS2 = CLOCK_MCHP_SAME54_GCLK_EVSYS2,
	CLOCK_CONTROL_MCHP_V1_GCLK_EVSYS3 = CLOCK_MCHP_SAME54_GCLK_EVSYS3,
	CLOCK_CONTROL_MCHP_V1_GCLK_EVSYS4 = CLOCK_MCHP_SAME54_GCLK_EVSYS4,
	CLOCK_CONTROL_MCHP_V1_GCLK_EVSYS5 = CLOCK_MCHP_SAME54_GCLK_EVSYS5,
	CLOCK_CONTROL_MCHP_V1_GCLK_EVSYS6 = CLOCK_MCHP_SAME54_GCLK_EVSYS6,
	CLOCK_CONTROL_MCHP_V1_GCLK_EVSYS7 = CLOCK_MCHP_SAME54_GCLK_EVSYS7,
	CLOCK_CONTROL_MCHP_V1_GCLK_EVSYS8 = CLOCK_MCHP_SAME54_GCLK_EVSYS8,
	CLOCK_CONTROL_MCHP_V1_GCLK_EVSYS9 = CLOCK_MCHP_SAME54_GCLK_EVSYS9,
	CLOCK_CONTROL_MCHP_V1_GCLK_EVSYS10 = CLOCK_MCHP_SAME54_GCLK_EVSYS10,
	CLOCK_CONTROL_MCHP_V1_GCLK_EVSYS11 = CLOCK_MCHP_SAME54_GCLK_EVSYS11,
	CLOCK_CONTROL_MCHP_V1_GCLK_SERCOM2_CORE = CLOCK_MCHP_SAME54_GCLK_SERCOM2_CORE,
	CLOCK_CONTROL_MCHP_V1_GCLK_SERCOM3_CORE = CLOCK_MCHP_SAME54_GCLK_SERCOM3_CORE,
	CLOCK_CONTROL_MCHP_V1_GCLK_TCC0_TCC1 = CLOCK_MCHP_SAME54_GCLK_TCC0_TCC1,
	CLOCK_CONTROL_MCHP_V1_GCLK_TC2_TC3 = CLOCK_MCHP_SAME54_GCLK_TC2_TC3,
	CLOCK_CONTROL_MCHP_V1_GCLK_CAN0 = CLOCK_MCHP_SAME54_GCLK_CAN0,
	CLOCK_CONTROL_MCHP_V1_GCLK_CAN1 = CLOCK_MCHP_SAME54_GCLK_CAN1,
	CLOCK_CONTROL_MCHP_V1_GCLK_TCC2_TCC3 = CLOCK_MCHP_SAME54_GCLK_TCC2_TCC3,
	CLOCK_CONTROL_MCHP_V1_GCLK_TC4_TC5 = CLOCK_MCHP_SAME54_GCLK_TC4_TC5,
	CLOCK_CONTROL_MCHP_V1_GCLK_PDEC = CLOCK_MCHP_SAME54_GCLK_PDEC,
	CLOCK_CONTROL_MCHP_V1_GCLK_AC = CLOCK_MCHP_SAME54_GCLK_AC,
	CLOCK_CONTROL_MCHP_V1_GCLK_CCL = CLOCK_MCHP_SAME54_GCLK_CCL,
	CLOCK_CONTROL_MCHP_V1_GCLK_SERCOM4_CORE = CLOCK_MCHP_SAME54_GCLK_SERCOM4_CORE,
	CLOCK_CONTROL_MCHP_V1_GCLK_SERCOM5_CORE = CLOCK_MCHP_SAME54_GCLK_SERCOM5_CORE,
	CLOCK_CONTROL_MCHP_V1_GCLK_SERCOM6_CORE = CLOCK_MCHP_SAME54_GCLK_SERCOM6_CORE,
	CLOCK_CONTROL_MCHP_V1_GCLK_SERCOM7_CORE = CLOCK_MCHP_SAME54_GCLK_SERCOM7_CORE,
	CLOCK_CONTROL_MCHP_V1_GCLK_TCC4 = CLOCK_MCHP_SAME54_GCLK_TCC4,
	CLOCK_CONTROL_MCHP_V1_GCLK_TC6_TC7 = CLOCK_MCHP_SAME54_GCLK_TC6_TC7,
	CLOCK_CONTROL_MCHP_V1_GCLK_ADC0 = CLOCK_MCHP_SAME54_GCLK_ADC0,
	CLOCK_CONTROL_MCHP_V1_GCLK_ADC1 = CLOCK_MCHP_SAME54_GCLK_ADC1,
	CLOCK_CONTROL_MCHP_V1_GCLK_DAC = CLOCK_MCHP_SAME54_GCLK_DAC,
	CLOCK_CONTROL_MCHP_V1_GCLK_I2S0 = CLOCK_MCHP_SAME54_GCLK_I2S0,
	CLOCK_CONTROL_MCHP_V1_GCLK_I2S1 = CLOCK_MCHP_SAME54_GCLK_I2S1,
	CLOCK_CONTROL_MCHP_V1_GCLK_SDHC0 = CLOCK_MCHP_SAME54_GCLK_SDHC0,
	CLOCK_CONTROL_MCHP_V1_GCLK_SDHC1 = CLOCK_MCHP_SAME54_GCLK_SDHC1,
	CLOCK_CONTROL_MCHP_V1_GCLK_CM4_TRACE = CLOCK_MCHP_SAME54_GCLK_CM4_TRACE,
} clock_control_mchp_gclk_sys_t;

/* Peripheral configuration structure */
struct clock_control_mchp_mclk_configuration_t {
	uint8_t cpu_div;
	bool ahb[20];
	bool apba[16];
	bool apbb[12];
	bool apbc[12];
	bool apbd[12];
};
struct clock_control_mchp_oscctrl_configuration_t {
	/* XOSCCTRL 0-1 register */
	uint32_t xoscctrl[2];
	/* DFLLCTRLA register */
	uint8_t dfllctrla;
	/* DFLLCTRLB register */
	uint8_t dfllctrlb;
	/* DFLLVAL register */
	uint32_t dfllval;
	/* DFLLMUL register */
	uint32_t dfllmul;
	/* DPLLCTRLA 0-1 register */
	uint8_t dpllctrla[2];
	/* DPLLRATIO 0-1 register */
	uint32_t dpllratio[2];
	/* DPLLCTRLB 0-1 register */
	uint8_t dpllctrlb[2];
};
struct clock_control_mchp_osc32kctrl_configuration_t {
	/* RTCCTRL register */
	uint8_t rtcctrl;
	/* XOSC32K register */
	uint16_t xosc32k;
	/* CFDCTRL register */
	uint8_t cfdctrl;
	/* OSCULP32K register */
	uint32_t osculp32k;
};
struct clock_control_mchp_gclk_configuration_t {
	/* GENCTRL 0-11 register */
	uint32_t genctrl[12];
	/* PCHCTRL 0-47 register */
	uint32_t pchctrl[48];
};
struct clock_control_mchp_configuration_t {
	struct clock_control_mchp_mclk_configuration_t *mclk_configuration;
	struct clock_control_mchp_oscctrl_configuration_t *oscctrl_configuration;
	struct clock_control_mchp_osc32kctrl_configuration_t *osc32kctrl_configuration;
	struct clock_control_mchp_gclk_configuration_t *gclk_configuration;
};

struct clock_control_mchp_mclk_rate_t {
	uint8_t cpu_div;
};
struct clock_control_mchp_oscctrl_rate_t {
	uint16_t dfll_mul_factor;
	bool is_dfll_closed_loop;
	uint16_t dpll_xosc_div[2];
	uint16_t dpll_ldr[2];
	uint8_t dpll_ldrfrac[2];
};
struct clock_control_mchp_osc32kctrl_rate_t {
	uint8_t xosc32k_cfd_presc;
};
struct clock_control_mchp_gclk_rate_t {
	bool div_sel[12];
	uint16_t gen_div[12];
};
struct clock_control_mchp_rate_t {
	struct clock_control_mchp_mclk_rate_t *mclk_rate;
	struct clock_control_mchp_oscctrl_rate_t *oscctrl_rate;
	struct clock_control_mchp_osc32kctrl_rate_t *osc32kctrl_rate;
	struct clock_control_mchp_gclk_rate_t *gclk_rate;
};

#endif /* CONFIG_SOC_SERIES_MCHP_SAME54 */

#endif /* ZEPHYR_INCLUDE_DRIVERS_CLOCK_CONTROL_CLOCK_CONTROL_MCHP_V1_H_ */
