/*
 * Copyright (c) 2024 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef ZEPHYR_INCLUDE_DRIVERS_CLOCK_CONTROL_CLOCK_CONTROL_ATMEL_SAM0_SYS_H_
#define ZEPHYR_INCLUDE_DRIVERS_CLOCK_CONTROL_CLOCK_CONTROL_ATMEL_SAM0_SYS_H_

/** @brief Clocks handled by the CLK peripheral.
 *
 * Clock types which can be used as a sys argument in clock_control API.
 */
typedef enum {
	CLOCK_CONTROL_SAM0_SUB_SYS_BEGIN = 0,
	// OSCCTRL Clock Controller
	CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_BEGIN,
	CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_XOSC0,
	CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_XOSC1,
	CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_END,

	CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_DFLL_BEGIN,
	CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_DFLL,
	CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_DFLL_END,

	CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_FDPLL_BEGIN,
	CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_FDPLL0,
	CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_FDPLL1,
	CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_FDPLL_END,

	// OSC32KCTRL Clock Controller
	CLOCK_CONTROL_SAM0_SUB_SYS_OSC32KCTRL_BEGIN,
	CLOCK_CONTROL_SAM0_SUB_SYS_OSC32KCTRL_XOSC32K,
	CLOCK_CONTROL_SAM0_SUB_SYS_OSC32KCTRL_XOSC1K,
	CLOCK_CONTROL_SAM0_SUB_SYS_OSC32KCTRL_RTC,
	CLOCK_CONTROL_SAM0_SUB_SYS_OSC32KCTRL_END,

	// GCLK Controller
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK_BEGIN,
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK0,
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK1,
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK2,
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK3,
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK4,
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK5,
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK6,
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK7,
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK8,
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK9,
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK10,
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK11,
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK_END,

	// MCLK Controller
	CLOCK_CONTROL_SAM0_SUB_SYS_MCLK_BEGIN,
	CLOCK_CONTROL_SAM0_SUB_SYS_MCLK_CPU,
	CLOCK_CONTROL_SAM0_SUB_SYS_MCLK_LOW_POWER,
	CLOCK_CONTROL_SAM0_SUB_SYS_MCLK_BACKUP,
	CLOCK_CONTROL_SAM0_SUB_SYS_MCLK_HIGH_SPEED,
	CLOCK_CONTROL_SAM0_SUB_SYS_MCLK_END,

	// Peripheral Clocks which needs GCLK as input
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_BEGIN,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_OSCCTRL_DFLL48,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_OSCCTRL_FDPLL0,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_OSCCTRL_FDPLL1,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_OSCCTRL_SLOW,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_EIC,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_FREQM_MSR,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_FREQM_REF,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_SERCOM0_CORE,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_SERCOM1_CORE,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_TC0_TC1,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_USB,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_EVSYS0,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_EVSYS1,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_EVSYS2,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_EVSYS3,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_EVSYS4,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_EVSYS5,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_EVSYS6,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_EVSYS7,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_EVSYS8,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_EVSYS9,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_EVSYS10,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_EVSYS11,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_SERCOM2_CORE,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_SERCOM3_CORE,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_TCC0_TCC1,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_TC2_TC3,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_CAN0,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_CAN1,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_TCC2_TCC3,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_TC4_TC5,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_PDEC,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_AC,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_CCL,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_SERCOM4_CORE,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_SERCOM5_CORE,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_SERCOM6_CORE,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_SERCOM7_CORE,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_TCC4,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_TC6_TC7,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_ADC0,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_ADC1,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_DAC,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_I2S0,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_I2S1,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_SDHC0,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_SDHC1,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_CM4_TRACE,
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_END,

	// AHB Clock
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_BEGIN,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_NVMCTRL_CACHE,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_NVMCTRL_SMEEPROM,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_QSPI_2X,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_PUKCC,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_CAN0,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_CAN1,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_SDHC0,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_SDHC1,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_GMAC,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_QSPI,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_PAC,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_USB,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_DMAC,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_CMCC,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_NVMCTRL,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_DSU,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_HPB3,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_HPB2,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_HPB1,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_HPB0,
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_END,

	// APB Clocks
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_BEGIN,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_TC0,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_TC1,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_SERCOM0,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_SERCOM1,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_FREQM,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_EIC,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_RTC,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_WDT,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_GCLK,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_SUPC,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_OSC32KCTRL,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_OSCCTRL,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_RSTC,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_MCLK,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_PM,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_PAC,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_RAMECC,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_TC2,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_TC3,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_TCC0,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_TCC1,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_SERCOM3,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_SECOM2,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_EVSYS,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_PORT,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_NVMCTRL,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_DSU,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_USB,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_CCL,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_QSPI,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_ICM,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_TRNG,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_AES,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_AC,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_PDEC,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_TC5,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_TC4,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_TCC3,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_TCC2,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_GMAC,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_PCC,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_I2S,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_DAC,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_ADC1,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_ADC0,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_TC7,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_TC6,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_TCC4,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_SERCOM7,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_SERCOM6,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_SERCOM5,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_SERCOM4,
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_END,
	CLOCK_CONTROL_SAM0_SUB_SYS_END,
} clock_control_sam0_sub_sys;

#define CLOCK_CONTROL_SAM0_SUB_SYS_LEN                                                             \
	CLOCK_CONTROL_SAM0_SUB_SYS_END - CLOCK_CONTROL_SAM0_SUB_SYS_BEGIN - 1
#define CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_LEN                                                     \
	CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_END - CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_BEGIN - 1
#define CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_DFLL_LEN                                                \
	CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_DFLL_END -                                              \
		CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_DFLL_BEGIN - 1
#define CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_FDPLL_LEN                                               \
	CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_FDPLL_END -                                             \
		CLOCK_CONTROL_SAM0_SUB_SYS_OSCCTRL_FDPLL_BEGIN - 1
#define CLOCK_CONTROL_SAM0_SUB_SYS_OSC32KCTRL_LEN                                                  \
	CLOCK_CONTROL_SAM0_SUB_SYS_OSC32KCTRL_END - CLOCK_CONTROL_SAM0_SUB_SYS_OSC32KCTRL_BEGIN - 1
#define CLOCK_CONTROL_SAM0_SUB_SYS_GCLK_LEN                                                        \
	CLOCK_CONTROL_SAM0_SUB_SYS_GCLK_END - CLOCK_CONTROL_SAM0_SUB_SYS_GCLK_BEGIN - 1
#define CLOCK_CONTROL_SAM0_SUB_SYS_MCLK_LEN                                                        \
	CLOCK_CONTROL_SAM0_SUB_SYS_MCLK_END - CLOCK_CONTROL_SAM0_SUB_SYS_MCLK_BEGIN - 1
#define CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_LEN                                                      \
	CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_END - CLOCK_CONTROL_SAM0_SUB_SYS_PERIPH_BEGIN - 1
#define CLOCK_CONTROL_SAM0_SUB_SYS_AHB_LEN                                                         \
	CLOCK_CONTROL_SAM0_SUB_SYS_AHB_END - CLOCK_CONTROL_SAM0_SUB_SYS_AHB_BEGIN - 1
#define CLOCK_CONTROL_SAM0_SUB_SYS_APB_LEN                                                         \
	CLOCK_CONTROL_SAM0_SUB_SYS_APB_END - CLOCK_CONTROL_SAM0_SUB_SYS_APB_BEGIN - 1

#endif /* ZEPHYR_INCLUDE_DRIVERS_CLOCK_CONTROL_CLOCK_CONTROL_ATMEL_SAM0_SYS_H_ */
